name: Share data between jobs

on: [push]

jobs:
  job_1:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Add 3 and 7
    runs-on: ${{ matrix.os }}
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.os }} > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: math-homework.txt

  job_2:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value
